#!/usr/bin/env python3
"""Build js/daab-phone-codes.js from ISO list + public country phone-code data."""
from __future__ import annotations

import json
import re
import urllib.request

from _paths import ROOT

COUNTRY_CODES_JS = ROOT / "js" / "daab-country-codes.js"
OUT = ROOT / "js" / "daab-phone-codes.js"
SOURCE_URL = (
    "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/"
    "master/json/countries.json"
)


def load_iso_codes() -> list[str]:
    text = COUNTRY_CODES_JS.read_text(encoding="utf-8")
    match = re.search(r"var CODES = \[(.*?)\];", text, re.S)
    if not match:
        raise SystemExit("Could not parse DAAB_COUNTRY_CODES from daab-country-codes.js")
    return [c.strip().strip('"') for c in match.group(1).split(",") if c.strip()]


def normalize_dial(raw: str) -> str:
    merged = str(raw or "").strip().replace(" ", "")
    if not merged:
        return ""
    if not merged.startswith("+"):
        merged = "+" + merged
    return merged


def fetch_phone_by_iso2() -> dict[str, str]:
    request = urllib.request.Request(
        SOURCE_URL,
        headers={"User-Agent": "DAAB-site-build/1.0"},
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        rows = json.load(response)
    by_iso2: dict[str, str] = {}
    for row in rows:
        iso2 = str(row.get("iso2") or "").upper()
        dial = normalize_dial(str(row.get("phonecode") or ""))
        if iso2 and dial and iso2 not in by_iso2:
            by_iso2[iso2] = dial
    return by_iso2


def build_entries(iso_codes: list[str], by_iso2: dict[str, str]) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    missing: list[str] = []
    for code in iso_codes:
        dial = by_iso2.get(code)
        if not dial:
            missing.append(code)
            continue
        entries.append((code, dial))
    if missing:
        print(f"Warning: no phone code for {len(missing)} ISO codes: {', '.join(missing)}")
    entries.sort(key=lambda item: (item[0], item[1]))
    return entries


def render_js(entries: list[tuple[str, str]]) -> str:
    lines = [
        "/**",
        " * ISO country calling codes for DAAB forms (membership application, etc.).",
        " * Generated by helpers/_build_phone_codes_js.py — do not edit by hand.",
        " * Load before daab-membership-application.js.",
        " */",
        "(function (global) {",
        '  "use strict";',
        "",
        "  /** @type {Array<[string, string]>} [cca2, e164] */",
        "  var ENTRIES = [",
    ]
    for code, dial in entries:
        lines.append(f'    ["{code}", "{dial}"],')
    lines.extend(
        [
            "  ];",
            "",
            "  function flagSrc(assetRoot, cc) {",
            '    if (!cc || cc.length !== 2) return "";',
            "    var root = String(assetRoot || \"\");",
            '    if (root && !/\\/$/.test(root)) root += "/";',
            '    return root + "images/flags/4x3/" + String(cc).toLowerCase() + ".svg";',
            "  }",
            "",
            "  global.DAAB_PHONE_CODES = ENTRIES;",
            "  global.DAAB_PHONE_FLAG_SRC = flagSrc;",
            '})(typeof window !== "undefined" ? window : this);',
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    iso_codes = load_iso_codes()
    by_iso2 = fetch_phone_by_iso2()
    entries = build_entries(iso_codes, by_iso2)
    OUT.write_text(render_js(entries), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(entries)} calling-code entries)")


if __name__ == "__main__":
    main()
