#!/usr/bin/env python3
"""Build a production-ready /Deployment folder from the repo (respects .deployignore).

Run from repository root:
    python helpers/_build_deployment_folder.py
"""
from __future__ import annotations

import fnmatch
import shutil
import sys
from pathlib import Path

from _paths import ROOT

DEPLOY_DIR = ROOT / "Deployment"
DEPLOYIGNORE = ROOT / ".deployignore"

# Always exclude (even if not listed in .deployignore)
HARD_EXCLUDES = {
    "Deployment",
    ".git",
    "node_modules",
    ".cursor",
    ".vscode",
    ".github",
    "__pycache__",
}

EXTRA_FILE_GLOBS = ("*.zip", "*.docx", "*.tmp", "~$*", "*.pyc", "*.pyo")
EXTRA_DIR_NAMES = {".git", "__pycache__", "node_modules"}


def parse_deployignore(path: Path) -> tuple[list[str], list[str]]:
    excludes: list[str] = []
    includes: list[str] = []
    if not path.is_file():
        return excludes, includes
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("!"):
            includes.append(line[1:].strip())
        else:
            excludes.append(line)
    return excludes, includes


def _match_rule(rel_posix: str, rule: str) -> bool:
    rule = rule.replace("\\", "/").strip()
    if not rule:
        return False
    if rule.endswith("/"):
        return rel_posix.startswith(rule) or rel_posix + "/" == rule
    if rule.endswith("/*"):
        prefix = rule[:-2]
        return rel_posix == prefix or rel_posix.startswith(prefix + "/")
    if "/" in rule or "*" in rule or "?" in rule:
        return fnmatch.fnmatch(rel_posix, rule)
    # bare name: file at any depth or top-level segment
    if rel_posix == rule:
        return True
    if rel_posix.endswith("/" + rule):
        return True
    return rule in rel_posix.split("/")


def should_exclude(rel_posix: str, excludes: list[str], includes: list[str]) -> bool:
    parts = rel_posix.split("/")
    if parts[0] in HARD_EXCLUDES or any(p in EXTRA_DIR_NAMES for p in parts):
        return True
    name = parts[-1]
    for pat in EXTRA_FILE_GLOBS:
        if fnmatch.fnmatch(name, pat):
            return True

    excluded = False
    for rule in excludes:
        if _match_rule(rel_posix, rule):
            excluded = True
            break

    if excluded:
        for rule in includes:
            if _match_rule(rel_posix, rule):
                return False
        return True
    return False


def collect_deploy_files() -> tuple[list[Path], list[Path]]:
    excludes, includes = parse_deployignore(DEPLOYIGNORE)
    included: list[Path] = []
    skipped: list[Path] = []
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file():
            continue
        try:
            rel = path.relative_to(ROOT)
        except ValueError:
            continue
        rel_posix = rel.as_posix()
        if should_exclude(rel_posix, excludes, includes):
            skipped.append(path)
        else:
            included.append(path)
    return included, skipped


def write_deployment_readme(counts: dict[str, int]) -> None:
    text = f"""# DAAB / WAAS — production deployment package

Generated by `python helpers/_build_deployment_folder.py`.

Upload **the contents of this folder** to the web server document root
(e.g. `/var/www/daab-waas/` or public_html).

## Included ({counts['files']} files)

| Path | Role |
|------|------|
| `index.html` | Language gateway |
| `az/`, `en/` | Live HTML pages (bilingual tree) |
| `css/` | Stylesheets |
| `js/` | Client scripts + gallery manifests |
| `images/` | Photos, logos, QR codes, gallery |
| `i18n/` | Navigation, routes, search, UI strings |
| `forum_2024/*.pdf` | Forum book download |

## Not included

Maintenance tools (`helpers/`), internal docs (`documents/`), archives (`_archive/`),
build sources (`az/application/`, `en/application/`), Word/markdown sources, and
other paths listed in `.deployignore`.

## After upload

1. Hard-refresh the site (`Ctrl+F5`).
2. Test `az/index.html`, `en/index.html`, scientists profiles, one forum page.
3. Confirm forum book PDF downloads from `az/forum/2024/index.html`.

Regenerate this folder whenever you prepare a release.
"""
    (DEPLOY_DIR / "README-DEPLOY.txt").write_text(text, encoding="utf-8")


def validate_deployment_tree() -> int:
    import _paths
    import _validate_site as vs

    _paths.ROOT = DEPLOY_DIR
    vs.ROOT = DEPLOY_DIR
    vs.BILINGUAL_PAGES = vs.bilingual_html_files()
    return vs.main()


def main() -> int:
    print("DAAB deployment package builder\n")
    print(f"  Source: {ROOT}")
    print(f"  Output: {DEPLOY_DIR}\n")

    # Preflight on source
    print("→ Validating source site…")
    pre = __import__("subprocess").run(
        [sys.executable, str(ROOT / "helpers" / "_validate_site.py")],
        cwd=ROOT,
    )
    if pre.returncode != 0:
        print("Source validation failed — fix errors before building Deployment/.")
        return 1

    included, skipped = collect_deploy_files()

    if DEPLOY_DIR.exists():
        print("→ Removing previous Deployment/ …")
        shutil.rmtree(DEPLOY_DIR)

    DEPLOY_DIR.mkdir(parents=True)
    copied = 0
    bytes_total = 0
    for src in included:
        rel = src.relative_to(ROOT)
        dest = DEPLOY_DIR / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        copied += 1
        bytes_total += src.stat().st_size

    write_deployment_readme({"files": copied})

    print(f"→ Copied {copied} files ({bytes_total / (1024 * 1024):.1f} MB)")
    print(f"→ Skipped {len(skipped)} non-deploy paths\n")

    # Spot-check required roots
    required = [
        "index.html",
        "az/index.html",
        "en/index.html",
        "css/daab-common.css",
        "js/daab-nav.js",
        "i18n/nav.json",
        "images/daab-logo.svg",
    ]
    missing_roots = [p for p in required if not (DEPLOY_DIR / p).is_file()]
    if missing_roots:
        print("ERROR — deployment package missing required files:")
        for p in missing_roots:
            print(f"  ✗ {p}")
        return 1

    print("→ Validating Deployment/ link integrity…")
    if validate_deployment_tree() != 0:
        print("\nDeployment package validation FAILED.")
        return 1

    print(f"\nOK — Deployment/ is ready ({copied} files).")
    print("Upload everything inside Deployment/ to your production web root.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
