#!/usr/bin/env python3
"""One-shot: rename photos-gallery albums/files to kebab-case ASCII paths.

Renames under images/photos-gallery/ only. Deletes _thumbs/ so it can be
regenerated by helpers/_build_photos_gallery_thumbs.py afterward.
"""
from __future__ import annotations

import re
import shutil
from pathlib import Path

from _paths import ROOT

GALLERY_ROOT = ROOT / "images" / "photos-gallery"

FOLDER_MAP: dict[str, str] = {
    "1.AlleyOfHonor": "1-alley-of-honor",
    "2.OpeningDay": "2-opening-day",
    "3.BookExibition": "3-book-exhibition",
    "4.Discussions": "4-discussions",
    "5. BetweenSessions": "5-between-sessions",
    "6. Portraits": "6-portraits",
    "7. Garabagh": "7-garabagh",
    "8. CoffeeBreak": "8-coffee-break",
    "9. LunchBreak": "9-lunch-break",
    "10. Party": "10-party",
}

# New folder → basename prefix for formerly spaced / non-ASCII files
FILE_PREFIX: dict[str, str] = {
    "5-between-sessions": "between-sessions",
    "7-garabagh": "garabagh",
    "10-party": "party",
}

EXTS = {".jpg", ".jpeg", ".png", ".webp"}


def needs_file_rename(name: str) -> bool:
    if " " in name or any(ord(c) > 127 for c in name):
        return True
    # Normalize mixed-case extensions and IMG_* leftovers.
    stem, ext = Path(name).stem, Path(name).suffix.lower()
    if Path(name).suffix != ext:
        return True
    if stem.upper().startswith("IMG_"):
        return True
    return False


def target_filename(new_folder: str, old_name: str) -> str:
    """Map an original filename to a kebab-case .jpg basename."""
    prefix = FILE_PREFIX.get(new_folder)
    stem = Path(old_name).stem
    ext = ".jpg"

    if not prefix:
        # Folder already had kebab files — keep stem, normalize extension.
        return f"{stem}{ext}" if Path(old_name).suffix.lower() in EXTS else old_name

    # IMG_8314 → garabagh-img-8314
    m_img = re.match(r"^IMG[_-]?(\d+)$", stem, re.I)
    if m_img:
        return f"{prefix}-img-{m_img.group(1)}{ext}"

    # 017-1. Title / 0010. Title / 002 Title / 029 Title
    m = re.match(r"^0*(\d+)(?:-([A-Za-z0-9]+))?(?:\b|[.\s_-])", stem)
    if m:
        num = int(m.group(1))
        suffix = m.group(2)
        width = 3 if num < 1000 else len(str(num))
        base = f"{prefix}-{num:0{width}d}"
        if suffix:
            base = f"{base}-{suffix.lower()}"
        return f"{base}{ext}"

    # Fallback: slugify remaining stem
    slug = re.sub(r"[^a-z0-9]+", "-", stem.lower()).strip("-")
    return f"{prefix}-{slug or 'photo'}{ext}"


def rename_files_in_folder(folder: Path, new_folder_name: str) -> int:
    renamed = 0
    files = [f for f in folder.iterdir() if f.is_file() and f.suffix.lower() in EXTS]
    # Phase 1: move to unique temp names to avoid collisions
    temps: list[tuple[Path, str]] = []
    for src in files:
        if not needs_file_rename(src.name) and src.suffix == ".jpg":
            continue
        dest_name = target_filename(new_folder_name, src.name)
        if dest_name == src.name:
            continue
        tmp = folder / f".__renaming_{renamed:04d}__{dest_name}"
        src.rename(tmp)
        temps.append((tmp, dest_name))
        renamed += 1

    # Phase 2: final names
    for tmp, dest_name in temps:
        dest = folder / dest_name
        if dest.exists():
            raise SystemExit(f"Collision: {dest.relative_to(ROOT)}")
        tmp.rename(dest)
    return renamed


def main() -> int:
    if not GALLERY_ROOT.is_dir():
        raise SystemExit(f"Missing {GALLERY_ROOT}")

    # Refuse to run if already renamed
    if (GALLERY_ROOT / "1-alley-of-honor").is_dir() and not (
        GALLERY_ROOT / "1.AlleyOfHonor"
    ).is_dir():
        print("Already kebab-case — nothing to do.")
        return 0

    total_files = 0
    for old_name, new_name in FOLDER_MAP.items():
        src = GALLERY_ROOT / old_name
        if not src.is_dir():
            print(f"  skip missing: {old_name}")
            continue
        n = rename_files_in_folder(src, new_name)
        total_files += n
        dest = GALLERY_ROOT / new_name
        if dest.exists():
            raise SystemExit(f"Destination exists: {dest}")
        src.rename(dest)
        print(f"  {old_name} -> {new_name} ({n} file renames)")

    thumbs = GALLERY_ROOT / "_thumbs"
    if thumbs.is_dir():
        shutil.rmtree(thumbs)
        print("  removed _thumbs/ (regenerate next)")

    # Sanity: no spaces left in album paths
    leftover = [
        str(p.relative_to(ROOT))
        for p in GALLERY_ROOT.rglob("*")
        if p.is_file() and " " in str(p.relative_to(GALLERY_ROOT))
    ]
    if leftover:
        print(f"WARNING: {len(leftover)} paths still contain spaces:")
        for line in leftover[:20]:
            print(" ", line)
        return 1

    print(f"Done. Folder renames: {len(FOLDER_MAP)}, file renames: {total_files}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
